version: '3.8'

services:
  app:
    build: .
    image: mini-mundo
    container_name: mini-mundo
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_NAME: mini_mundo
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mini_mundo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge